spring:
  application.name: TuneHeavenAnalytics
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:tuneheaven
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

file:
  import-dir: /Users/jacek/IdeaProjects/TuneHeavenAnalytics/import
  export-dir: /Users/jacek/IdeaProjects/TuneHeavenAnalytics/export